### ISSUE TITLE
p2p value?

### ISSUE THREAD

**Issue by jaredthesovereign** [equitrader/Equitrade#2]
Is there a specific p2p port to use and peermagic value for the conf file?  using uNOMP.

I use 43103 but uNOMP still throws:

Pool verge Thread # p2p connection failed - likely incorrect host or port

My pool configuration is:

"p2p": {
"enabled": true,
"host": "127.0.0.1",
"port": 43103,
"disableTransactions": false
},

My conf is fairly straightforward:

rpcuser=x
rpcpassword=x
server=1
daemon=1
rpcport=43102
port=43103

I've also tried different ports and obviously my host is the localhost 127.0.0.1 Thoughts?

**Comment by jaredthesovereign** [comment]
Resolved.  For future reference peerMagic value=b4f8e7a5

**Comment by cryptozeny** [comment]
in my case, if i use `-connect=` with running daemon, it reports the error.
